### ISSUE TITLE
Implement SVGO plugin

### ISSUE THREAD

**Issue by umar-tophat** [tophat/react-vector-graphics#6]
Depends on #5 

Applies SVGO to optimize the contents of the SVG file.

**Comment by umar-ahmed** [comment]
@iamogbz Is this task unnecessary now? If I'm understanding the changes you made correctly, we can just re-use `@svgr/plugin-svgo`?

**Comment by iamogbz** [comment]
@umar-ahmed yeah it's probably not any more. Will wait and then close this.

**Comment by iamogbz** [comment]
Closed in #21
